### ISSUE TITLE
Is there a roadmap for One UI?

### ISSUE THREAD

**Issue by rafiuske** [SamsungInternet/OneUI-Web#22]
Is there a roadmap for One UI?

- new components
- guidelines

**Comment by PicchiKevin** [comment]
Hi Rafael,

Here is a general roadmap: https://oneuiweb.dev/#/roadmap ([source code](https://github.com/SamsungInternet/OneUI-Web/blob/gh-pages/roadmap.md))

Feel free to contribute to the project <3
